sudo add-apt-repository --yes "deb http://dl.google.com/linux/chrome/deb/ stable main"
sudo add-apt-repository --yes "deb http://dl.google.com/linux/chrome-remote-desktop/deb/ stable main"
sudo add-apt-repository --yes "deb http://dl.google.com/linux/deb/ stable main non-free"
sudo add-apt-repository --yes "deb http://dl.google.com/linux/earth/deb/ stable main"
sudo add-apt-repository --yes "deb http://dl.google.com/linux/musicmanager/deb/ stable main"
sudo add-apt-repository --yes "deb http://dl.google.com/linux/talkplugin/deb/ stable main"
sudo add-apt-repository --yes "deb http://download.virtualbox.org/virtualbox/debian precise contrib"
sudo add-apt-repository --yes "deb http://download.webmin.com/download/repository sarge contrib"
sudo add-apt-repository --yes "deb http://repo.ajenti.org/ng/debian main main ubuntu"
sudo add-apt-repository --yes ppa:3xx0/cloudster
sudo add-apt-repository --yes ppa:7-seven/lossless-cut
sudo add-apt-repository --yes ppa:9v-shaun-42/networkmanager
sudo add-apt-repository --yes ppa:aalmenar/apache
sudo add-apt-repository --yes ppa:aalmenar/openssl
sudo add-apt-repository --yes ppa:aap/cam
sudo add-apt-repository --yes ppa:aarch64-laptops/all
sudo add-apt-repository --yes ppa:aaronr/spacewalk
sudo add-apt-repository --yes ppa:abelcheung/lucid-dev-backports
sudo add-apt-repository --yes ppa:acbf-development-team/acbf
sudo add-apt-repository --yes ppa:achadwick/mypaint-testing
sudo add-apt-repository --yes ppa:acshk/stable
sudo add-apt-repository --yes ppa:ad5001/accountfree
sudo add-apt-repository --yes ppa:adamwolf/kicad-trusty-backports
sudo add-apt-repository --yes ppa:adrian-wilkins/kyoto-cabinet
sudo add-apt-repository --yes ppa:adrozdoff/cmake
sudo add-apt-repository --yes ppa:adrozdoff/ffmpeg-opti
sudo add-apt-repository --yes ppa:adrozdoff/mingw
sudo add-apt-repository --yes ppa:adrozdoff/qtcreator-git
sudo add-apt-repository --yes ppa:agilelaw/nginx
sudo add-apt-repository --yes ppa:ajf/trg
sudo add-apt-repository --yes ppa:akhavr/dash-electrum-builddeps
sudo add-apt-repository --yes ppa:alcacoop/asterisk
sudo add-apt-repository --yes ppa:aleksander-m/modemmanager-trusty
sudo add-apt-repository --yes ppa:aleksander-m/modemmanager-xenial
sudo add-apt-repository --yes ppa:alexatilbrook/ppa
sudo add-apt-repository --yes ppa:alexei.colin/opencv
sudo add-apt-repository --yes ppa:alexharrington/php-zmq
sudo add-apt-repository --yes ppa:alexmurray/indicator-sensors-daily
sudo add-apt-repository --yes ppa:alex-p/azpainter
sudo add-apt-repository --yes ppa:alex-p/clementine
sudo add-apt-repository --yes ppa:alex-p/deadbeef
sudo add-apt-repository --yes ppa:alivema4ever/multimedia
sudo add-apt-repository --yes ppa:amaurycarvalho/caslink3
sudo add-apt-repository --yes ppa:ancestris/ancestris-unstable
sudo add-apt-repository --yes ppa:andreas-h/emacs
sudo add-apt-repository --yes ppa:andvgal/firehol-bpo
sudo add-apt-repository --yes ppa:andykimpe/idm
sudo add-apt-repository --yes ppa:angel-berlanas/intel-lucid
sudo add-apt-repository --yes ppa:ansible/ansible-2.7
sudo add-apt-repository --yes ppa:ansible/ansible-2.8
sudo add-apt-repository --yes ppa:ansible/ansible-2.9
sudo add-apt-repository --yes ppa:anton+/dnscrypt
sudo add-apt-repository --yes ppa:ap10336/ppa
sudo add-apt-repository --yes ppa:apandada1/brightness-controller
sudo add-apt-repository --yes ppa:appgrid/stable
sudo add-apt-repository --yes ppa:application-indicator-upstream/ppa
sudo add-apt-repository --yes ppa:appneta/ppa
sudo add-apt-repository --yes ppa:arctus/ppa
sudo add-apt-repository --yes ppa:arnd-arndnet/icinga
sudo add-apt-repository --yes ppa:artyom.h31/3proxy
sudo add-apt-repository --yes ppa:arune/auml-atom-daily
sudo add-apt-repository --yes ppa:arunsivaraman/gpuviewer
sudo add-apt-repository --yes ppa:arx/snapshot
sudo add-apt-repository --yes ppa:ast/389
sudo add-apt-repository --yes ppa:astraljava/lucid
sudo add-apt-repository --yes ppa:ast/softether-test
sudo add-apt-repository --yes ppa:atareao/caja-extensions
sudo add-apt-repository --yes ppa:auanswers/lts-backported-kernels-prerelease
sudo add-apt-repository --yes ppa:audio-recorder/ppa
sudo add-apt-repository --yes ppa:autoload/ppa
sudo add-apt-repository --yes ppa:autopilot/1.5
sudo add-apt-repository --yes ppa:awg/emacs-updates
sudo add-apt-repository --yes ppa:ayourk/xenial-backports
sudo add-apt-repository --yes ppa:bbot+core+developers/ppa
sudo add-apt-repository --yes ppa:bderzhavets/experimental
sudo add-apt-repository --yes ppa:beardoverflow/telegram-desktop
sudo add-apt-repository --yes ppa:beardoverflow/ts3client
sudo add-apt-repository --yes ppa:bedouin/mawakit
sudo add-apt-repository --yes ppa:bedouin/ppa
sudo add-apt-repository --yes ppa:beeswax/trusty
sudo add-apt-repository --yes ppa:beevm/nagios4
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.0-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.0-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.0-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.1-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.1-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.2-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.2-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.3-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.11.3-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.0-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.0-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.1-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.1-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.2-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.2-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-bionic
sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt562-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt563-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt571-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt58-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt591-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt592-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt593-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt594-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt595-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt596-xenial
sudo add-apt-repository --yes ppa:beineri/opt-qt597-xenial
sudo add-apt-repository --yes ppa:belin/trusty
sudo add-apt-repository --yes ppa:bemdevops/curl-backport
sudo add-apt-repository --yes ppa:bemdevops/puppet-backport
sudo add-apt-repository --yes ppa:benkai/precise-unity-backport
sudo add-apt-repository --yes ppa:bertrand-pietu/frescobaldi
sudo add-apt-repository --yes ppa:bibledit/beta
sudo add-apt-repository --yes ppa:bibledit/ppa
sudo add-apt-repository --yes ppa:biblepay-official/mainnet
sudo add-apt-repository --yes ppa:biblepay-official/testnet
sudo add-apt-repository --yes ppa:billy-olsen/kilo-lp1515278
sudo add-apt-repository --yes ppa:billy-olsen/lp1728739
sudo add-apt-repository --yes ppa:billy-olsen/test-kernels-bionic
sudo add-apt-repository --yes ppa:billy-olsen/xl2tpd-lp1760796
sudo add-apt-repository --yes ppa:biohazara/bio-linux
sudo add-apt-repository --yes ppa:bitcoin-abc/ppa
sudo add-apt-repository --yes ppa:bitcoin/bitcoin
sudo add-apt-repository --yes ppa:bitcoin-unlimited/bucash
sudo add-apt-repository --yes ppa:bitpusher/ppa
sudo add-apt-repository --yes ppa:bit-team/stable
sudo add-apt-repository --yes ppa:bit-team/testing
sudo add-apt-repository --yes ppa:bjori/php5
sudo add-apt-repository --yes ppa:bjori/php5-daily
sudo add-apt-repository --yes ppa:blr/nodejs-4-lts-deps
sudo add-apt-repository --yes ppa:blueleaflinux/ppa
sudo add-apt-repository --yes ppa:bluesabre/pulseaudio-a2dp
sudo add-apt-repository --yes ppa:bluesabre/raspbian-xfce4.14
sudo add-apt-repository --yes ppa:b-mike-n/burstsms-kannel
sudo add-apt-repository --yes ppa:boesbadwolf/desktop.disk-image
sudo add-apt-repository --yes ppa:bojo42/vpnc
sudo add-apt-repository --yes ppa:bo-vircio/zimbra
sudo add-apt-repository --yes ppa:brad-froehle/backports
sudo add-apt-repository --yes ppa:brad-froehle/llvm-backports
sudo add-apt-repository --yes ppa:brad-marshall/check-mk
sudo add-apt-repository --yes ppa:brandonsnider/lessfs
sudo add-apt-repository --yes ppa:brcha/mongodb-backports
sudo add-apt-repository --yes ppa:broder/reptyr
sudo add-apt-repository --yes ppa:broken/ppa
sudo add-apt-repository --yes ppa:bryanquigley/1796501
sudo add-apt-repository --yes ppa:bryce/backports
sudo add-apt-repository --yes ppa:bryce/librabbitmq-sru-1790657
sudo add-apt-repository --yes ppa:bryce/xen-sru-1823441
sudo add-apt-repository --yes ppa:bshum/postgresql
sudo add-apt-repository --yes ppa:bstudent/nvidia-graphics-drivers-396.26-copy-of-staging-
sudo add-apt-repository --yes ppa:bstudent/nvidia-graphics-drivers-396.26-copy-of-staging-ppa-20180522
sudo add-apt-repository --yes ppa:budgie-remix/nautilus-downgrade
sudo add-apt-repository --yes ppa:bugs-launchpad-net-falkensweb/cool-retro-term
sudo add-apt-repository --yes ppa:buzzlightyear/dev
sudo add-apt-repository --yes ppa:byteit101/frc-toolchain
sudo add-apt-repository --yes ppa:bzamecnik/poppler
sudo add-apt-repository --yes ppa:caffeine-developers/caffeine-dev
sudo add-apt-repository --yes ppa:caffeine-developers/ppa
sudo add-apt-repository --yes ppa:cafuego/inkscape
sudo add-apt-repository --yes ppa:cafuego/inkscape-lucid-depends
sudo add-apt-repository --yes ppa:cafuego/lucid-backports
sudo add-apt-repository --yes ppa:cafuego/lucid-gcc
sudo add-apt-repository --yes ppa:caicai8/lbreakouthd-unofficial
sudo add-apt-repository --yes ppa:caicai8/lpairs2-unofficial
sudo add-apt-repository --yes ppa:caio1982/golang151trusty
sudo add-apt-repository --yes ppa:caio1982/golang153trusty
sudo add-apt-repository --yes ppa:caio1982/python34crypto26precise
sudo add-apt-repository --yes ppa:campusexplorer/builddeps
sudo add-apt-repository --yes ppa:canonical-bootstack/trusty-mitaka
sudo add-apt-repository --yes ppa:canonical-foundations/openjdk11-stage2
sudo add-apt-repository --yes ppa:canonical-foundations/openjdk9-stage1
sudo add-apt-repository --yes ppa:canonical-hwe-team/sputnik-kernel
sudo add-apt-repository --yes ppa:canonical-kernel-team/bootstrap
sudo add-apt-repository --yes ppa:canonical-kernel-team/builder-extra
sudo add-apt-repository --yes ppa:canonical-losas/golang153trusty
sudo add-apt-repository --yes ppa:canonical-x/x-staging
sudo add-apt-repository --yes ppa:cardapio-team/cardapio-ppa
sudo add-apt-repository --yes ppa:carsten-schlote/ppa-cdemu
sudo add-apt-repository --yes ppa:carsten-uppenbrink-net/dovecot
sudo add-apt-repository --yes ppa:carsten-uppenbrink-net/nginx
sudo add-apt-repository --yes ppa:carsten-uppenbrink-net/openssl
sudo add-apt-repository --yes ppa:carsten-uppenbrink-net/postfix
sudo add-apt-repository --yes ppa:cassou/emacs
sudo add-apt-repository --yes ppa:catalystit/haproxy-1.5
sudo add-apt-repository --yes ppa:catfish-search/catfish-stable
sudo add-apt-repository --yes ppa:ccheney/libimobiledevice
sudo add-apt-repository --yes ppa:centriq-team/lp1732804
sudo add-apt-repository --yes ppa:centrych/kernel
sudo add-apt-repository --yes ppa:centrych/kernel-proposed
sudo add-apt-repository --yes ppa:certbot/certbot
sudo add-apt-repository --yes ppa:certbot/certbot-build
sudo add-apt-repository --yes ppa:c.falco/alpha
sudo add-apt-repository --yes ppa:cginternals/backports-ppa
sudo add-apt-repository --yes ppa:cginternals/ppa
sudo add-apt-repository --yes ppa:channelgrabberltd/php-bionic
sudo add-apt-repository --yes ppa:checkbox-dev/testing
sudo add-apt-repository --yes ppa:chiluk/lp1758736
sudo add-apt-repository --yes ppa:chimerarevo/vlc-lucid
sudo add-apt-repository --yes ppa:chimeratk/ppa
sudo add-apt-repository --yes ppa:chris-love/diamond
sudo add-apt-repository --yes ppa:chromium-team/beta
sudo add-apt-repository --yes ppa:chromium-team/dev
sudo add-apt-repository --yes ppa:chromixium/dev
sudo add-apt-repository --yes ppa:cis/beta
sudo add-apt-repository --yes ppa:cis/stable
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3094
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3629
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3650
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3658
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3690
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3729
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3734
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3747
sudo add-apt-repository --yes ppa:ci-train-ppa-service/3782
sudo add-apt-repository --yes ppa:clearpath-robotics/vitamixx
sudo add-apt-repository --yes ppa:cloud-it/ppa
sudo add-apt-repository --yes ppa:cmsj/nintendoswitch
sudo add-apt-repository --yes ppa:cmue81/ppa
sudo add-apt-repository --yes ppa:cnugteren/clblast
sudo add-apt-repository --yes ppa:codemonkey941/tsglxenial
sudo add-apt-repository --yes ppa:coffee-team/coffee
sudo add-apt-repository --yes ppa:colineos/testing
sudo add-apt-repository --yes ppa:colin-king/powermanagement
sudo add-apt-repository --yes ppa:colin-king/zfs-disco
sudo add-apt-repository --yes ppa:commendsarnex/winedri3
sudo add-apt-repository --yes ppa:costales/anoise
sudo add-apt-repository --yes ppa:costales/caja
sudo add-apt-repository --yes ppa:createsc/3beol
sudo add-apt-repository --yes ppa:criu/ppa
sudo add-apt-repository --yes ppa:croscondevops/collectd-latest
sudo add-apt-repository --yes ppa:csaba-kertesz/random
sudo add-apt-repository --yes ppa:cszikszoy/upnp
sudo add-apt-repository --yes ppa:cubic-wizard/development
sudo add-apt-repository --yes ppa:cubic-wizard/release
sudo add-apt-repository --yes ppa:cumulus-team/cumulus
sudo add-apt-repository --yes ppa:cybermax-dexter/vulkan-backports
sudo add-apt-repository --yes ppa:cybersec/panto-linux-theme-xenial
sudo add-apt-repository --yes ppa:cybersec/panto-tools-xenial-v1
sudo add-apt-repository --yes ppa:cyphermox/crack
sudo add-apt-repository --yes ppa:cyphermox/efi
sudo add-apt-repository --yes ppa:cz.nic-labs/bird
sudo add-apt-repository --yes ppa:d042888-2/samba-4.10.0
sudo add-apt-repository --yes ppa:dahbien-hwa/cmake-latest
sudo add-apt-repository --yes ppa:dajhorn/gcc-3
sudo add-apt-repository --yes ppa:dannyedel/dspdfviewer
sudo add-apt-repository --yes ppa:dannyedel/dspdfviewer-daily-lucid
sudo add-apt-repository --yes ppa:dannyedel/dspdfviewer-lucid
sudo add-apt-repository --yes ppa:dannyedel/lucid-hacks
sudo add-apt-repository --yes ppa:danser/samba-cluster
sudo add-apt-repository --yes ppa:dansmith/chirp-snapshots
sudo add-apt-repository --yes ppa:dasom/ppa
sudo add-apt-repository --yes ppa:david-gabriel/ppa
sudo add-apt-repository --yes ppa:dddddddddddddddddd/38438
sudo add-apt-repository --yes ppa:ddstreet/lp1454286
sudo add-apt-repository --yes ppa:ddstreet/lp1545173
sudo add-apt-repository --yes ppa:ddstreet/lp1557673
sudo add-apt-repository --yes ppa:ddstreet/lp1571075
sudo add-apt-repository --yes ppa:ddstreet/lp1658491
sudo add-apt-repository --yes ppa:deadsnakes/nightly
sudo add-apt-repository --yes ppa:deadsnakes/ppa
sudo add-apt-repository --yes ppa:deb-rob/ros-bionic
sudo add-apt-repository --yes ppa:deb-rob/ros-xenial
sudo add-apt-repository --yes ppa:deity/sid
sudo add-apt-repository --yes ppa:designate-ppa/havana
sudo add-apt-repository --yes ppa:devon-r/graphicsmagick
sudo add-apt-repository --yes ppa:dgadomski/cups
sudo add-apt-repository --yes ppa:dgadomski/indicator-sensors
sudo add-apt-repository --yes ppa:diana-deployment/precise-test
sudo add-apt-repository --yes ppa:divius/ppa
sudo add-apt-repository --yes ppa:dlech/keepass2-plugins
sudo add-apt-repository --yes ppa:dluxen/cmake-backports
sudo add-apt-repository --yes ppa:dmitrins/nginx-brotli-backports
sudo add-apt-repository --yes ppa:dns/gnustep
sudo add-apt-repository --yes ppa:doctormo/efl
sudo add-apt-repository --yes ppa:dolik-rce/upp-nightly
sudo add-apt-repository --yes ppa:dominik-stadler/dsta-bionic-ppa
sudo add-apt-repository --yes ppa:dominik-stadler/dsta-lucid-ppa
sudo add-apt-repository --yes ppa:dominik-stadler/dsta-precise-ppa
sudo add-apt-repository --yes ppa:dominik-stadler/dsta-trusty-ppa
sudo add-apt-repository --yes ppa:dominik-stadler/dsta-xenial-ppa
sudo add-apt-repository --yes ppa:dosemu2/ppa
sudo add-apt-repository --yes ppa:dr-graef/pd-l2ork.bionic
sudo add-apt-repository --yes ppa:dr-graef/pd-l2ork.disco
sudo add-apt-repository --yes ppa:dr-graef/pd-l2ork.trusty
sudo add-apt-repository --yes ppa:dr-graef/pd-l2ork.xenial
sudo add-apt-repository --yes ppa:dr-graef/pure-lang.bionic
sudo add-apt-repository --yes ppa:dr-graef/pure-lang.disco
sudo add-apt-repository --yes ppa:dr-graef/pure-lang.xenial
sudo add-apt-repository --yes ppa:dr-graef/test.xenial
sudo add-apt-repository --yes ppa:dschaerf/myubuntu
sudo add-apt-repository --yes ppa:du9l/ngx-pagespeed
sudo add-apt-repository --yes ppa:duclvzz/compiz-preproposed
sudo add-apt-repository --yes ppa:edgar2705/my-ppa
sudo add-apt-repository --yes ppa:emblem-parade/prudence
sudo add-apt-repository --yes ppa:embrosyn/cinnamon
sudo add-apt-repository --yes ppa:embrosyn/xapps
sudo add-apt-repository --yes ppa:emerginovteam/emerginov
sudo add-apt-repository --yes ppa:emoraes25/cid
sudo add-apt-repository --yes ppa:eosrei/fonts
sudo add-apt-repository --yes ppa:eudoxos/woo-daily
sudo add-apt-repository --yes ppa:eugenesan/ppa
sudo add-apt-repository --yes ppa:ezyang/ppa
sudo add-apt-repository --yes ppa:fabianarias/ejabberd
sudo add-apt-repository --yes ppa:fabianarias/gitolite
sudo add-apt-repository --yes ppa:fabianarias/kernel
sudo add-apt-repository --yes ppa:fabianarias/nginx
sudo add-apt-repository --yes ppa:fabianarias/php5
sudo add-apt-repository --yes ppa:falk-t-j/alfresco
sudo add-apt-repository --yes ppa:falk-t-j/games
sudo add-apt-repository --yes ppa:falk-t-j/lucid-kde35
sudo add-apt-repository --yes ppa:fantonifabio/cinnamon-experimental
sudo add-apt-repository --yes ppa:fantonifabio/cinnamon-testing
sudo add-apt-repository --yes ppa:faster3ck/converseen
sudo add-apt-repository --yes ppa:fbirlik/kscope
sudo add-apt-repository --yes ppa:feng-kylin/1904
sudo add-apt-repository --yes ppa:feng-kylin/1904tmp
sudo add-apt-repository --yes ppa:ferramroberto/extra
sudo add-apt-repository --yes ppa:ferramroberto/linuxfreedomlucid
sudo add-apt-repository --yes ppa:ferramroberto/lucidgame
sudo add-apt-repository --yes ppa:ferramroberto/lucidtest
sudo add-apt-repository --yes ppa:ferramroberto/precise
sudo add-apt-repository --yes ppa:finitelife/ppa
sudo add-apt-repository --yes ppa:fixnix/indicator-systemtray-unity
sudo add-apt-repository --yes ppa:fklassen/appneta
sudo add-apt-repository --yes ppa:flexiondotorg/audio
sudo add-apt-repository --yes ppa:fmauneko/fuse
sudo add-apt-repository --yes ppa:format-junkie-team/release
sudo add-apt-repository --yes ppa:fossfreedom/nautilus
sudo add-apt-repository --yes ppa:fossfreedom/rhythmbox
sudo add-apt-repository --yes ppa:frederic-loui/p4lang-bionic
sudo add-apt-repository --yes ppa:frederic-loui/p4lang-master-bionic-nightly
sudo add-apt-repository --yes ppa:freecad-community/ppa
sudo add-apt-repository --yes ppa:freefilesync/ffs
sudo add-apt-repository --yes ppa:freefilesync/ffs-build-precise
sudo add-apt-repository --yes ppa:furmanek/cindergpfs
sudo add-apt-repository --yes ppa:furmanek/cindergpfs-mitaka
sudo add-apt-repository --yes ppa:fziegler/support
sudo add-apt-repository --yes ppa:gagarin/disco
sudo add-apt-repository --yes ppa:garhuy/precise
sudo add-apt-repository --yes ppa:garteneden/nemo-extensions
sudo add-apt-repository --yes ppa:garteneden/nemo-extensions-dep-trusty
sudo add-apt-repository --yes ppa:gen3r1cuser/graphicsmagick
sudo add-apt-repository --yes ppa:gencfsm/ppa
sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
sudo add-apt-repository --yes ppa:george-edison55/gcc4.7-precise
sudo add-apt-repository --yes ppa:george-edison55/go-1.7
sudo add-apt-repository --yes ppa:gert-die/trusty-mia
sudo add-apt-repository --yes ppa:gertvdijk/keepassx-backports
sudo add-apt-repository --yes ppa:gertvdijk/openvpn-backports
sudo add-apt-repository --yes ppa:gezakovacs/boost
sudo add-apt-repository --yes ppa:gislab-npo/development
sudo add-apt-repository --yes ppa:git-core/ppa
sudo add-apt-repository --yes ppa:gma500/emgd
sudo add-apt-repository --yes ppa:gnome3-team/gnome3-staging
sudo add-apt-repository --yes ppa:gnu-psychosynth-team/ppa
sudo add-apt-repository --yes ppa:gophers/archive
sudo add-apt-repository --yes ppa:gophers/testing
sudo add-apt-repository --yes ppa:gpiccoli/lps1795659-1824981
sudo add-apt-repository --yes ppa:guessi/resource-agents
sudo add-apt-repository --yes ppa:guimalufb/gvpe
sudo add-apt-repository --yes ppa:happyaron/kernel
sudo add-apt-repository --yes ppa:hartb/ppa
sudo add-apt-repository --yes ppa:hda-me/dirty-fix
sudo add-apt-repository --yes ppa:hda-me/higan
sudo add-apt-repository --yes ppa:hda-me/legacy-gala
sudo add-apt-repository --yes ppa:hda-me/meek
sudo add-apt-repository --yes ppa:hda-me/pinentry
sudo add-apt-repository --yes ppa:hda-me/qt5ct
sudo add-apt-repository --yes ppa:hda-me/zulucrypt
sudo add-apt-repository --yes ppa:hectane/go-1.6
sudo add-apt-repository --yes ppa:hectane/hectane
sudo add-apt-repository --yes ppa:hectane/hectane-dev
sudo add-apt-repository --yes ppa:helioloureiro/ppa
sudo add-apt-repository --yes ppa:hennekn/favourite-backports
sudo add-apt-repository --yes ppa:hentenaar/php
sudo add-apt-repository --yes ppa:hentenaar/php5.4
sudo add-apt-repository --yes ppa:hermesinteractiva/auladigital
sudo add-apt-repository --yes ppa:hermesinteractiva/cga
sudo add-apt-repository --yes ppa:hermlnx/system-config-lvm
sudo add-apt-repository --yes ppa:hermlnx/xrdp
sudo add-apt-repository --yes ppa:hlprasu/lifeograph-xenial
sudo add-apt-repository --yes ppa:hluk/copyq
sudo add-apt-repository --yes ppa:hluk/copyq-beta
sudo add-apt-repository --yes ppa:hnakamur/binaryen
sudo add-apt-repository --yes ppa:hnakamur/boost
sudo add-apt-repository --yes ppa:holindho/avkernel
sudo add-apt-repository --yes ppa:hooghuis/ltspcluster-stable
sudo add-apt-repository --yes ppa:h-rayflood/gcc-lower
sudo add-apt-repository --yes ppa:h-rayflood/gcc-upper
sudo add-apt-repository --yes ppa:h-rayflood/llvm
sudo add-apt-repository --yes ppa:h-rayflood/llvm-upper
sudo add-apt-repository --yes ppa:hsoft/ppa
sudo add-apt-repository --yes ppa:hunter-kaller/ppa
sudo add-apt-repository --yes ppa:hurricanedefense/openssh
sudo add-apt-repository --yes ppa:hvr/cabal-staging
sudo add-apt-repository --yes ppa:hvr/ghcjs
sudo add-apt-repository --yes ppa:hyozd/serialplot
sudo add-apt-repository --yes ppa:hyperair/libmemcached-backports
sudo add-apt-repository --yes ppa:iacobs/pgbouncer
sudo add-apt-repository --yes ppa:ibmpackages/mldl
sudo add-apt-repository --yes ppa:ibro-x/asterisk-13.18-xenial
sudo add-apt-repository --yes ppa:ieseljust/bionic
sudo add-apt-repository --yes ppa:ievgeny/backports
sudo add-apt-repository --yes ppa:ievgeny/cctv-viewer
sudo add-apt-repository --yes ppa:igb/php54-precise
sudo add-apt-repository --yes ppa:igb/php54-trusty
sudo add-apt-repository --yes ppa:igb/php55-trusty
sudo add-apt-repository --yes ppa:igb/ppa-precise
sudo add-apt-repository --yes ppa:igb/ppa-trusty
sudo add-apt-repository --yes ppa:igb/precise
sudo add-apt-repository --yes ppa:imcode/s3ql-bionic
sudo add-apt-repository --yes ppa:indicator-multiload/daily
sudo add-apt-repository --yes ppa:indicator-multiload/stable-daily
sudo add-apt-repository --yes ppa:infie/boost-1.47
sudo add-apt-repository --yes ppa:infie/evotest
sudo add-apt-repository --yes ppa:internetbroadcasting/activemq-lucid
sudo add-apt-repository --yes ppa:internetbroadcasting/backports-lucid
sudo add-apt-repository --yes ppa:internetbroadcasting/packages-for-precise
sudo add-apt-repository --yes ppa:ionic/precise-updates
sudo add-apt-repository --yes ppa:isc/bind
sudo add-apt-repository --yes ppa:isc/bind-dev
sudo add-apt-repository --yes ppa:isc/bind-esv
sudo add-apt-repository --yes ppa:iscoolent/nginx
sudo add-apt-repository --yes ppa:itachi-san/ffmpeg
sudo add-apt-repository --yes ppa:itachi-san/freshplayerplugin
sudo add-apt-repository --yes ppa:itachi-san/gvfs-mtp
sudo add-apt-repository --yes ppa:ivaliullin/ansible-kubernetes
sudo add-apt-repository --yes ppa:ivanj/beanstalkd
sudo add-apt-repository --yes ppa:jakar/qt-heif
sudo add-apt-repository --yes ppa:jakobwilm/visionlibs
sudo add-apt-repository --yes ppa:jamesc-000/lucid-backports
sudo add-apt-repository --yes ppa:jamesf/lenovofixes
sudo add-apt-repository --yes ppa:james-page/juju-gccgo
sudo add-apt-repository --yes ppa:jan-hoffmann/fail2ban
sudo add-apt-repository --yes ppa:janisozaur/cmake-update
sudo add-apt-repository --yes ppa:janisozaur/rct2-deb
sudo add-apt-repository --yes ppa:jasonpleau/backports
sudo add-apt-repository --yes ppa:jbicha/arch
sudo add-apt-repository --yes ppa:jd-team/jdownloader
sudo add-apt-repository --yes ppa:jeff250/apmode
sudo add-apt-repository --yes ppa:jeff250/ppa
sudo add-apt-repository --yes ppa:jfi/ppa
sudo add-apt-repository --yes ppa:jgross-h/coq-8.10-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-8.5-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-8.6-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-8.7-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-8.8-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-8.9-daily
sudo add-apt-repository --yes ppa:jgross-h/coq-master-daily
sudo add-apt-repository --yes ppa:jhammen/bipscript
sudo add-apt-repository --yes ppa:jincreator/unity
sudo add-apt-repository --yes ppa:jjo/discoproject
sudo add-apt-repository --yes ppa:jkordik-4/gnmrc-ppa
sudo add-apt-repository --yes ppa:jlamarh/bionic-ppa
sudo add-apt-repository --yes ppa:jmcarthur-rabid/ppa-network-manager-precise
sudo add-apt-repository --yes ppa:joemullally/backport-alsa-hda-dkms
sudo add-apt-repository --yes ppa:joestringer/ppa
sudo add-apt-repository --yes ppa:joe-yasi/dolphin-emu
sudo add-apt-repository --yes ppa:joey-imbasciano/collectd5
sudo add-apt-repository --yes ppa:johnf-inodes/m3u8-segmenter
sudo add-apt-repository --yes ppa:jonathonf/gcc-5.5
sudo add-apt-repository --yes ppa:jonathonf/gcc-6.5
sudo add-apt-repository --yes ppa:jonathonf/gcc-8.2
sudo add-apt-repository --yes ppa:jonathonf/gcc-defaults-utopic
sudo add-apt-repository --yes ppa:jonathonf/mate-1.16
sudo add-apt-repository --yes ppa:jonathonf/mate-1.19
sudo add-apt-repository --yes ppa:jonathonf/mate-1.19-gtk3.22
sudo add-apt-repository --yes ppa:jonathonf/mate-1.20
sudo add-apt-repository --yes ppa:jonathonf/mate-1.20-gtk3.22
sudo add-apt-repository --yes ppa:jonathonf/mate-1.22
sudo add-apt-repository --yes ppa:jonathonf/microcode
sudo add-apt-repository --yes ppa:jonathonf/nightcode
sudo add-apt-repository --yes ppa:jonathonf/vlc-3
sudo add-apt-repository --yes ppa:jonlar/grub2
sudo add-apt-repository --yes ppa:joseluisblancoc/mrpt
sudo add-apt-repository --yes ppa:jrnewell/dh-golang
sudo add-apt-repository --yes ppa:jsalisbury/1792195
sudo add-apt-repository --yes ppa:jschwender/optional
sudo add-apt-repository --yes ppa:jspringer/lightdm-vpn-trusty
sudo add-apt-repository --yes ppa:jwigley/window-list
sudo add-apt-repository --yes ppa:kalakris/autofs
sudo add-apt-repository --yes ppa:kalakris/cmake
sudo add-apt-repository --yes ppa:kalakris/eigen
sudo add-apt-repository --yes ppa:kalakris/okular
sudo add-apt-repository --yes ppa:kalon33/ppa
sudo add-apt-repository --yes ppa:kamalmostafa/linux-kamal-dellstudio
sudo add-apt-repository --yes ppa:kamalmostafa/linux-kamal-i915bri
sudo add-apt-repository --yes ppa:kamalmostafa/lp897421-unfreeze-deadlock
sudo add-apt-repository --yes ppa:kazam-team/unstable-series
sudo add-apt-repository --yes ppa:kb1jwq/elasticsearch
sudo add-apt-repository --yes ppa:kde3-maintainers/trinity-svn-nightly
sudo add-apt-repository --yes ppa:kdenlive/kdenlive-stable
sudo add-apt-repository --yes ppa:keepassx/daily
sudo add-apt-repository --yes ppa:keithw/mosh
sudo add-apt-repository --yes ppa:keks9n/skypetab
sudo add-apt-repository --yes ppa:kelleyk/compton
sudo add-apt-repository --yes ppa:kelleyk/curl
sudo add-apt-repository --yes ppa:kelleyk/emacs
sudo add-apt-repository --yes ppa:kernsuite/kern-4
sudo add-apt-repository --yes ppa:kernsuite/kern-5
sudo add-apt-repository --yes ppa:kernsuite/kern-dev
sudo add-apt-repository --yes ppa:kevin-demarco/scrimmage-bionic
sudo add-apt-repository --yes ppa:ki7mt/jtsdk
sudo add-apt-repository --yes ppa:ki7mt/wsjtx
sudo add-apt-repository --yes ppa:ki7mt/wsjtx-next
sudo add-apt-repository --yes ppa:kirillshkrogalev/ffmpeg-next
sudo add-apt-repository --yes ppa:klaus-vormweg/awesome
sudo add-apt-repository --yes ppa:klaus-vormweg/bluefish-snapshots
sudo add-apt-repository --yes ppa:klaviyo/backports
sudo add-apt-repository --yes ppa:klich-lukasz/kleewho
sudo add-apt-repository --yes ppa:kmscherer/gitolite3
sudo add-apt-repository --yes ppa:kocio/mapnik
sudo add-apt-repository --yes ppa:kojoley/boost
sudo add-apt-repository --yes ppa:k-peter/tectonic-ci
sudo add-apt-repository --yes ppa:krisives/breezeenhanced
sudo add-apt-repository --yes ppa:krusot2016/appstest
sudo add-apt-repository --yes ppa:kubuntu-ppa/experimental
sudo add-apt-repository --yes ppa:kxstudio-team/openoctave
sudo add-apt-repository --yes ppa:landronimirc/xfce
sudo add-apt-repository --yes ppa:launcher-list-indicator/ppa
sudo add-apt-repository --yes ppa:launchpad-weyland/xserver-nobackfill
sudo add-apt-repository --yes ppa:laurent-boulard/i3
sudo add-apt-repository --yes ppa:laurent-boulard/ppa
sudo add-apt-repository --yes ppa:lavrandy/bitcoin-core
sudo add-apt-repository --yes ppa:lbsolost/ppa
sudo add-apt-repository --yes ppa:leaeasy/dde
sudo add-apt-repository --yes ppa:lekensteyn/wacom-tablet
sudo add-apt-repository --yes ppa:leonbo/golang
sudo add-apt-repository --yes ppa:leppa/backports
sudo add-apt-repository --yes ppa:libreoffice/libreoffice-6-2
sudo add-apt-repository --yes ppa:life-ru/lxctl
sudo add-apt-repository --yes ppa:linaro-maintainers/toolchain
sudo add-apt-repository --yes ppa:linbit/linbit-drbd9-stack
sudo add-apt-repository --yes ppa:linrunner/tlp
sudo add-apt-repository --yes ppa:linux-phc/ppa
sudo add-apt-repository --yes ppa:linux-phc/testing
sudo add-apt-repository --yes ppa:lkoppel/ceres
sudo add-apt-repository --yes ppa:lkoppel/robotics
sudo add-apt-repository --yes ppa:lkoppel/robotics-wavelab
sudo add-apt-repository --yes ppa:longsleep/couchdb-precise-backport
sudo add-apt-repository --yes ppa:lorenzo-milesi/zabbix30-precise
sudo add-apt-repository --yes ppa:lovell/cosmic-backports
sudo add-apt-repository --yes ppa:lovell/xenial-backports
sudo add-apt-repository --yes ppa:lubuntu-dev/lubuntu-daily
sudo add-apt-repository --yes ppa:lucid-bleed/ppa
sudo add-apt-repository --yes ppa:luke-jr/bitcoinknots
sudo add-apt-repository --yes ppa:luke-jr/db48
sudo add-apt-repository --yes ppa:lukycrociato/chromium-va-api
sudo add-apt-repository --yes ppa:maarten-fonville/android-build-tools
sudo add-apt-repository --yes ppa:maarten-fonville/android-studio
sudo add-apt-repository --yes ppa:maas-maintainers/maas-ephemeral-images
sudo add-apt-repository --yes ppa:maas/proposed
sudo add-apt-repository --yes ppa:maas/stable
sudo add-apt-repository --yes ppa:maciej-puzio/backports
sudo add-apt-repository --yes ppa:madsa/misc
sudo add-apt-repository --yes ppa:mail2nitishgupta/ppa
sudo add-apt-repository --yes ppa:mail6543210/backports
sudo add-apt-repository --yes ppa:makson96/fglrx
sudo add-apt-repository --yes ppa:makson96/recultis
sudo add-apt-repository --yes ppa:maktio/amule-bionic-or-newer
sudo add-apt-repository --yes ppa:maktio/compiz-reloaded
sudo add-apt-repository --yes ppa:malcscott/perdition
sudo add-apt-repository --yes ppa:malizor/lift
sudo add-apt-repository --yes ppa:mandel/movie-tracker
sudo add-apt-repository --yes ppa:marenhachmann/pango
sudo add-apt-repository --yes ppa:marko-preuss/hibiscus
sudo add-apt-repository --yes ppa:marko-techytalk.info/ralink-wireless
sudo add-apt-repository --yes ppa:mark-pcnetspec/dxvk
sudo add-apt-repository --yes ppa:mark-pcnetspec/lutris-bionic
sudo add-apt-repository --yes ppa:mark-pcnetspec/nemo-3.6-testing
sudo add-apt-repository --yes ppa:martinx/enlightenment
sudo add-apt-repository --yes ppa:mathieu-simon/lts-backports
sudo add-apt-repository --yes ppa:matt-colyer/nodejs
sudo add-apt-repository --yes ppa:matt-leotta/vxl
sudo add-apt-repository --yes ppa:mbaum2000/avant-window-navigator
sudo add-apt-repository --yes ppa:mbaynton/trafficserver
sudo add-apt-repository --yes ppa:mc3man/avidemux1
sudo add-apt-repository --yes ppa:mc3man/fdkaac-encoder
sudo add-apt-repository --yes ppa:mc3man/mpv-tests
sudo add-apt-repository --yes ppa:mc3man/nauty-hacks1
sudo add-apt-repository --yes ppa:mc3man/testing6
sudo add-apt-repository --yes ppa:metlov/ejabberd-gssapi
sudo add-apt-repository --yes ppa:mgrocock/nginx
sudo add-apt-repository --yes ppa:mgrocock/openssl
sudo add-apt-repository --yes ppa:mhier/libboost-latest
sudo add-apt-repository --yes ppa:mhier/libwt-latest
sudo add-apt-repository --yes ppa:mhorn/git
sudo add-apt-repository --yes ppa:michaelh1/lucid-updates
sudo add-apt-repository --yes ppa:michael-ruoss/kmymoney
sudo add-apt-repository --yes ppa:micove/console
sudo add-apt-repository --yes ppa:mikepurvis/ceres
sudo add-apt-repository --yes ppa:mikepurvis/docs
sudo add-apt-repository --yes ppa:mikepurvis/dpkg
sudo add-apt-repository --yes ppa:mikepurvis/network
sudo add-apt-repository --yes ppa:mir-team/release
sudo add-apt-repository --yes ppa:mithro/personal
sudo add-apt-repository --yes ppa:mixxx/mixxx
sudo add-apt-repository --yes ppa:mjasnik/ppa
sudo add-apt-repository --yes ppa:mmstick76/alacritty
sudo add-apt-repository --yes ppa:morphis/anbox-support
sudo add-apt-repository --yes ppa:mozgiii/iscsi
sudo add-apt-repository --yes ppa:mozgiii/wpa3
sudo add-apt-repository --yes ppa:mpandersen/shorewall-backport
sudo add-apt-repository --yes ppa:mpanella/i915-hacks
sudo add-apt-repository --yes ppa:mpanella/libguestfs
sudo add-apt-repository --yes ppa:mpanella/mutt
sudo add-apt-repository --yes ppa:mpanella/password-store
sudo add-apt-repository --yes ppa:mpanella/tmux
sudo add-apt-repository --yes ppa:mpanella/virt-manager
sudo add-apt-repository --yes ppa:mrazavi/gvm
sudo add-apt-repository --yes ppa:mss/couchdb
sudo add-apt-repository --yes ppa:msulikowski/valgrind
sudo add-apt-repository --yes ppa:mtron/kaffeine-git
sudo add-apt-repository --yes ppa:mtron/kaffeine-stable
sudo add-apt-repository --yes ppa:mymedia/telegram
sudo add-apt-repository --yes ppa:mymolina/kalendas-pkg
sudo add-apt-repository --yes ppa:mythbuntu/0.29
sudo add-apt-repository --yes ppa:mythbuntu/30
sudo add-apt-repository --yes ppa:mythbuntu/31
sudo add-apt-repository --yes ppa:n00bsys0p/hirocoin
sudo add-apt-repository --yes ppa:narindergupta/burrow
sudo add-apt-repository --yes ppa:natecarlson/ffmpeg4
sudo add-apt-repository --yes ppa:natecarlson/gnome-backport
sudo add-apt-repository --yes ppa:natecarlson/graphite
sudo add-apt-repository --yes ppa:natecarlson/precisebackports
sudo add-apt-repository --yes ppa:nbritton/dpdk
sudo add-apt-repository --yes ppa:nbritton/dpdk-18.11
sudo add-apt-repository --yes ppa:nbritton/openvswitch
sudo add-apt-repository --yes ppa:neon1ks/bionic
sudo add-apt-repository --yes ppa:neon1ks/bump-xenial
sudo add-apt-repository --yes ppa:neon/kf5-snapshot-weekly
sudo add-apt-repository --yes ppa:neutstulen/password-store
sudo add-apt-repository --yes ppa:neutstulen/sip-tester
sudo add-apt-repository --yes ppa:nextcloud-devs/client
sudo add-apt-repository --yes ppa:nextcloud-devs/client-beta
sudo add-apt-repository --yes ppa:nginx/development
sudo add-apt-repository --yes ppa:nickmoline/php55
sudo add-apt-repository --yes ppa:nickstenning/elasticsearch
sudo add-apt-repository --yes ppa:nicolas-zin/halide
sudo add-apt-repository --yes ppa:nicolas-zin/ossec-ubuntu
sudo add-apt-repository --yes ppa:nicolaw/blip
sudo add-apt-repository --yes ppa:nightuser/qtcreator
sudo add-apt-repository --yes ppa:nightuser/sane-backends-backports
sudo add-apt-repository --yes ppa:nightuser/unity-systray
sudo add-apt-repository --yes ppa:nilarimogard/webupd8
sudo add-apt-repository --yes ppa:nmi/llvm-3.2
sudo add-apt-repository --yes ppa:nmi/llvm-3.3
sudo add-apt-repository --yes ppa:no1wantdthisname/ppa
sudo add-apt-repository --yes ppa:noobslab/indicators
sudo add-apt-repository --yes ppa:noobslab/themes
sudo add-apt-repository --yes ppa:notarrjay/fio-dkms
sudo add-apt-repository --yes ppa:notinsideofhereiamnotinside/bionicppa
sudo add-apt-repository --yes ppa:notinsideofhereiamnotinside/ppa
sudo add-apt-repository --yes ppa:nrbrtx/hdf5
sudo add-apt-repository --yes ppa:nrbrtx/scilab-deps
sudo add-apt-repository --yes ppa:nrbrtx/sysvinit-backlight
sudo add-apt-repository --yes ppa:ntadej/tano
sudo add-apt-repository --yes ppa:ntamas/opencv3
sudo add-apt-repository --yes ppa:nugulinux/sdk
sudo add-apt-repository --yes ppa:numediart/deps
sudo add-apt-repository --yes ppa:nutznboltz-deactivatedaccount/glusterfs3
sudo add-apt-repository --yes ppa:nutznboltz-deactivatedaccount/kvm-libvirt-lts
sudo add-apt-repository --yes ppa:nutznboltz-deactivatedaccount/working-grub2-on-virtio-disk-for-lts
sudo add-apt-repository --yes ppa:nvidia-vdpau/cutting-edge-multimedia
sudo add-apt-repository --yes ppa:nvidia-vdpau/ppa
sudo add-apt-repository --yes ppa:ochosi/pidgin-sipe
sudo add-apt-repository --yes ppa:ocontant/freeipa312
sudo add-apt-repository --yes ppa:oded-geek/lucid-server
sudo add-apt-repository --yes ppa:oibaf/gallium-nine
sudo add-apt-repository --yes ppa:oibaf/graphics-drivers
sudo add-apt-repository --yes ppa:oiteam/gcompris
sudo add-apt-repository --yes ppa:oiteam/kde
sudo add-apt-repository --yes ppa:olive-editor/ffmpeg
sudo add-apt-repository --yes ppa:openbravo-isv/ppa
sudo add-apt-repository --yes ppa:openchange/travis-deps
sudo add-apt-repository --yes ppa:openjdk-11-transition/fixes
sudo add-apt-repository --yes ppa:openoffice-pkgs/ppa
sudo add-apt-repository --yes ppa:openquake/saga
sudo add-apt-repository --yes ppa:openstack-ci-core/openafs-amd64-hwe
sudo add-apt-repository --yes ppa:openstack-ubuntu-testing/grizzly-build-depends
sudo add-apt-repository --yes ppa:openstreetmap-serbia/ppa
sudo add-apt-repository --yes ppa:ops-class/os161-toolchain
sudo add-apt-repository --yes ppa:orangain/opencv
sudo add-apt-repository --yes ppa:outsideopen/imagemagick
sudo add-apt-repository --yes ppa:p8n/precise-backports
sudo add-apt-repository --yes ppa:pali/graphics-drivers
sudo add-apt-repository --yes ppa:pali/graphics-drivers-stable
sudo add-apt-repository --yes ppa:pali/kdepim-noakonadi
sudo add-apt-repository --yes ppa:panda3d/ppa
sudo add-apt-repository --yes ppa:paolorotolo/copy
sudo add-apt-repository --yes ppa:papirus/papirus
sudo add-apt-repository --yes ppa:patrick-salecker/opencv
sudo add-apt-repository --yes ppa:paulo-matias/openjdk-lts-backports
sudo add-apt-repository --yes ppa:paulo-miguel-dias/mesa
sudo add-apt-repository --yes ppa:paulo-miguel-dias/pkppa
sudo add-apt-repository --yes ppa:pdffs/dovecot-backports
sudo add-apt-repository --yes ppa:pdffs/freetds-lucid-backports
sudo add-apt-repository --yes ppa:pdffs/precise-cobbler
sudo add-apt-repository --yes ppa:pdffs/precise-virt
sudo add-apt-repository --yes ppa:pdoes/dovecot
sudo add-apt-repository --yes ppa:pdoes/postfix
sudo add-apt-repository --yes ppa:pdoes/spamassassin
sudo add-apt-repository --yes ppa:pharmgkb/trusty
sudo add-apt-repository --yes ppa:philippe-latulippe/mpd
sudo add-apt-repository --yes ppa:pinta-maintainers/pinta-stable
sudo add-apt-repository --yes ppa:pi-rho/security
sudo add-apt-repository --yes ppa:piti-diablotin/abiout
sudo add-apt-repository --yes ppa:pkg-boinc/ppa
sudo add-apt-repository --yes ppa:pkg-games/wesnoth-devel
sudo add-apt-repository --yes ppa:pkg-ganeti-devel/lts
sudo add-apt-repository --yes ppa:pmjdebruijn/darktable-release
sudo add-apt-repository --yes ppa:pmjdebruijn/darktable-unstable
sudo add-apt-repository --yes ppa:pmjdebruijn/gimp-release
sudo add-apt-repository --yes ppa:pmjdebruijn/gnoduino-release
sudo add-apt-repository --yes ppa:pmjdebruijn/gnome-color-manager-release
sudo add-apt-repository --yes ppa:poliva/lightum-mba
sudo add-apt-repository --yes ppa:prasoc/ppa
sudo add-apt-repository --yes ppa:precise-python2.6-modules/ppa
sudo add-apt-repository --yes ppa:ps3love/lucid3
sudo add-apt-repository --yes ppa:ps3love/precise
sudo add-apt-repository --yes ppa:pxc/ppa
sudo add-apt-repository --yes ppa:qji/ax88179
sudo add-apt-repository --yes ppa:r0lf/stable
sudo add-apt-repository --yes ppa:r3dkn16h7/r3dkn16h7
sudo add-apt-repository --yes ppa:r3gis-r3gis/dvbhdhomerun
sudo add-apt-repository --yes ppa:raaa/ppa
sudo add-apt-repository --yes ppa:radio-astro/main
sudo add-apt-repository --yes ppa:radzaquiel/obs-studio
sudo add-apt-repository --yes ppa:rafaeldtinoco/lp1828495
sudo add-apt-repository --yes ppa:rafaeldtinoco/qemubackports
sudo add-apt-repository --yes ppa:rahmadani/bayu
sudo add-apt-repository --yes ppa:ravefinity-project/ppa
sudo add-apt-repository --yes ppa:razor-qt/ppa
sudo add-apt-repository --yes ppa:rbredereck/qtbase-opensource-src-duplexpatch
sudo add-apt-repository --yes ppa:rdratlos/autofs
sudo add-apt-repository --yes ppa:rdratlos/ppa-asusfix
sudo add-apt-repository --yes ppa:rebuntu16/other-stuff
sudo add-apt-repository --yes ppa:relan/exfat
sudo add-apt-repository --yes ppa:reviczky/context-daily
sudo add-apt-repository --yes ppa:rexut/recoil
sudo add-apt-repository --yes ppa:rhaist/hyperscan
sudo add-apt-repository --yes ppa:riccetn/aegisub
sudo add-apt-repository --yes ppa:rikmills/latte-dock
sudo add-apt-repository --yes ppa:rikmills/staging1
sudo add-apt-repository --yes ppa:rjvbertin/mesa
sudo add-apt-repository --yes ppa:rock-hopper/audiotools
sudo add-apt-repository --yes ppa:rohieb/ppa
sudo add-apt-repository --yes ppa:rpardini/adoptopenjdk
sudo add-apt-repository --yes ppa:rpardini/shorewall5x-backports
sudo add-apt-repository --yes ppa:rschroll/beru
sudo add-apt-repository --yes ppa:rsjtaylor/cmake-backports
sudo add-apt-repository --yes ppa:rsrchboy/builddeps
sudo add-apt-repository --yes ppa:rsrchboy/openssh
sudo add-apt-repository --yes ppa:rstephe/ppa
sudo add-apt-repository --yes ppa:russianneuromancer/baytrail
sudo add-apt-repository --yes ppa:rye/ubuntuone-extras
sudo add-apt-repository --yes ppa:saiarcot895/chromium-beta
sudo add-apt-repository --yes ppa:saiarcot895/chromium-dev
sudo add-apt-repository --yes ppa:salt-formulas/ppa
sudo add-apt-repository --yes ppa:samirkherraz/xbillboard-stable
sudo add-apt-repository --yes ppa:samvh/bluetooth-bionic-bp
sudo add-apt-repository --yes ppa:samvh/davmail-backport-bionic
sudo add-apt-repository --yes ppa:samvh/evolution-bionic-bp
sudo add-apt-repository --yes ppa:samvh/nwm-bionic-bp
sudo add-apt-repository --yes ppa:sandvine/cloud-archive-ocata
sudo add-apt-repository --yes ppa:sankari171987/usbcambionic
sudo add-apt-repository --yes ppa:satyajit-happy/themes
sudo add-apt-repository --yes ppa:savoury1/gparted
sudo add-apt-repository --yes ppa:savoury1/metamorphose2
sudo add-apt-repository --yes ppa:schot/gawk
sudo add-apt-repository --yes ppa:scottritchie/erlang-backports
sudo add-apt-repository --yes ppa:scottritchie/precise-rake-update
sudo add-apt-repository --yes ppa:scrappycocos/elementary-tweaks-fix
sudo add-apt-repository --yes ppa:screenfreeze/deskcon
sudo add-apt-repository --yes ppa:scribus/ppa
sudo add-apt-repository --yes ppa:sduddikunta/z580
sudo add-apt-repository --yes ppa:sebastian-stenzel/cryptomator
sudo add-apt-repository --yes ppa:secor941/santoku-bionic
sudo add-apt-repository --yes ppa:seitz-a/bionic
sudo add-apt-repository --yes ppa:serge-hallyn/lucid-kvm-test
sudo add-apt-repository --yes ppa:serge-hallyn/qemu-migration2
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/packages
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php44
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php44-modules
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php52
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php52-modules
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php53
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php53-modules
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php54
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php54-modules
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php55
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php55-modules
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php56
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php70
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/php71
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/qt48
sudo add-apt-repository --yes ppa:sergey-dryabzhinsky/toolchain
sudo add-apt-repository --yes ppa:severnt/subversion
sudo add-apt-repository --yes ppa:sevmek/ppa
sudo add-apt-repository --yes ppa:sharp/gajim
sudo add-apt-repository --yes ppa:shauns/mythtv
sudo add-apt-repository --yes ppa:shauns/mythtv-lucid-testing
sudo add-apt-repository --yes ppa:shemgp/gnome-flashback
sudo add-apt-repository --yes ppa:shemgp/lxd
sudo add-apt-repository --yes ppa:shemgp/xenial
sudo add-apt-repository --yes ppa:shuhao/fixed
sudo add-apt-repository --yes ppa:shuhao/xenialjdk7
sudo add-apt-repository --yes ppa:sicklylife/gtkhash
sudo add-apt-repository --yes ppa:silknetwork/silknetwork
sudo add-apt-repository --yes ppa:silverwave/testing0
sudo add-apt-repository --yes ppa:silverwave/testing2
sudo add-apt-repository --yes ppa:silverwave/testing6
sudo add-apt-repository --yes ppa:silverwave/testing8
sudo add-apt-repository --yes ppa:ska-sa/beta
sudo add-apt-repository --yes ppa:skettler/php
sudo add-apt-repository --yes ppa:skettler/puppet
sudo add-apt-repository --yes ppa:skunk/pepper-flash
sudo add-apt-repository --yes ppa:smathot/cogscinl
sudo add-apt-repository --yes ppa:smoser/lucid-kernel-upgrades
sudo add-apt-repository --yes ppa:snuspl/protobuf-250
sudo add-apt-repository --yes ppa:someone561/sweethome3d
sudo add-apt-repository --yes ppa:sonicwalker/gambas3
sudo add-apt-repository --yes ppa:splunk-cloud-accounts/go103-ppa
sudo add-apt-repository --yes ppa:spvkgn/mate-1.22
sudo add-apt-repository --yes ppa:sqrammi/mythtv-fixes
sudo add-apt-repository --yes ppa:sschuberth/build-tools
sudo add-apt-repository --yes ppa:staff-pro-unreal/roccat-tools
sudo add-apt-repository --yes ppa:stefanobalocco/blankon
sudo add-apt-repository --yes ppa:stefanobalocco/crobots
sudo add-apt-repository --yes ppa:stefanor/drupalmods
sudo add-apt-repository --yes ppa:stephane.magnenat/bionic
sudo add-apt-repository --yes ppa:stephane.magnenat/lucid
sudo add-apt-repository --yes ppa:streetcrypto7/leveldb
sudo add-apt-repository --yes ppa:streetcrypto7/rocksdb
sudo add-apt-repository --yes ppa:suawekk/monit
sudo add-apt-repository --yes ppa:sunab/kdenlive-svn
sudo add-apt-repository --yes ppa:surfernsk/internet-software
sudo add-apt-repository --yes ppa:sweptlaser/pyopengl
sudo add-apt-repository --yes ppa:sweptlaser/python3-pcl
sudo add-apt-repository --yes ppa:syncany/release
sudo add-apt-repository --yes ppa:systec/curl-7.35-trusty
sudo add-apt-repository --yes ppa:systec/haproxy-1.4.24-trusty
sudo add-apt-repository --yes ppa:systec/pound-2.6-trusty
sudo add-apt-repository --yes ppa:tah83/secp256k1
sudo add-apt-repository --yes ppa:tanyuliang2/baidunetdisk
sudo add-apt-repository --yes ppa:tarkhov/ppa
sudo add-apt-repository --yes ppa:tcpcloud/contrail-2.20
sudo add-apt-repository --yes ppa:tcpcloud/contrail-2.22
sudo add-apt-repository --yes ppa:tcpcloud/contrail-3.0
sudo add-apt-repository --yes ppa:tcpcloud/contrail-master
sudo add-apt-repository --yes ppa:tdb/utop-backports
sudo add-apt-repository --yes ppa:teejee2008/ppa
sudo add-apt-repository --yes ppa:testdrivelinux/lucid-backports
sudo add-apt-repository --yes ppa:teward/curl
sudo add-apt-repository --yes ppa:teward/xca
sudo add-apt-repository --yes ppa:teward/znc
sudo add-apt-repository --yes ppa:thebernmeister/ppa
sudo add-apt-repository --yes ppa:thedsweb/yawls-opencv
sudo add-apt-repository --yes ppa:thomas-schiex/blender
sudo add-apt-repository --yes ppa:thopiekar/rcraid
sudo add-apt-repository --yes ppa:threadsafegraphics/tsgl-dev
sudo add-apt-repository --yes ppa:tiagohillebrandt/postman
sudo add-apt-repository --yes ppa:tiagohillebrandt/vagrant
sudo add-apt-repository --yes ppa:tiagohillebrandt/wp-cli
sudo add-apt-repository --yes ppa:ticsenia/ppa
sudo add-apt-repository --yes ppa:tieto/kld
sudo add-apt-repository --yes ppa:tigerite/kernel
sudo add-apt-repository --yes ppa:tigerite/mint-xorg-update
sudo add-apt-repository --yes ppa:timchen119/bluez5-trusty
sudo add-apt-repository --yes ppa:timchen119/rtl8822bu
sudo add-apt-repository --yes ppa:timekpr-maintainers/ppa
sudo add-apt-repository --yes ppa:timo-jyrinki/qemu-virgl
sudo add-apt-repository --yes ppa:tista/adapta
sudo add-apt-repository --yes ppa:tista/adapta-nightly
sudo add-apt-repository --yes ppa:tista/plata-theme
sudo add-apt-repository --yes ppa:tjheeta/python
sudo add-apt-repository --yes ppa:tj-yxy/wallpaper-bionic
sudo add-apt-repository --yes ppa:tkchia/build-ia16
sudo add-apt-repository --yes ppa:tobix/epoxy
sudo add-apt-repository --yes ppa:tobydox/mingw-x-trusty
sudo add-apt-repository --yes ppa:tombeckmann/geary
sudo add-apt-repository --yes ppa:tomtomtom/gebabbel
sudo add-apt-repository --yes ppa:tomtomtom/ultrastar-deluxe
sudo add-apt-repository --yes ppa:tomylobo/maven
sudo add-apt-repository --yes ppa:toobaz/toobaz
sudo add-apt-repository --yes ppa:tormodvolden/m6809
sudo add-apt-repository --yes ppa:tormodvolden/ovcc
sudo add-apt-repository --yes ppa:touche-sign/hts-tvheadend
sudo add-apt-repository --yes ppa:towolf/carbon-c-relay
sudo add-apt-repository --yes ppa:towolf/monitoring-plugins
sudo add-apt-repository --yes ppa:towolf/nginx
sudo add-apt-repository --yes ppa:transmissionbt/ppa
sudo add-apt-repository --yes ppa:transmitsms/burstkannel
sudo add-apt-repository --yes ppa:trebelnik-stefina/radeon-profile-dependencies
sudo add-apt-repository --yes ppa:trebelnik-stefina/radeon-profile-dependencies-trusty
sudo add-apt-repository --yes ppa:tsgl-test/tsgl-dev
sudo add-apt-repository --yes ppa:tslocum/aafm
sudo add-apt-repository --yes ppa:tspindler/ecryptfs-utils
sudo add-apt-repository --yes ppa:tspindler/nm-0.9
sudo add-apt-repository --yes ppa:tualatrix/ppa
sudo add-apt-repository --yes ppa:tuleu/lucid-backports
sudo add-apt-repository --yes ppa:tuxpoldo/btsync
sudo add-apt-repository --yes ppa:txwikinger/php5.2
sudo add-apt-repository --yes ppa:ubuntu-audio-dev/alsa-daily
sudo add-apt-repository --yes ppa:ubuntubudgie-dev/budgie-extras-daily
sudo add-apt-repository --yes ppa:ubuntu-cloud-archive/tools
sudo add-apt-repository --yes ppa:ubuntu-desktop/canary-image
sudo add-apt-repository --yes ppa:ubuntu-desktop/gnome-software
sudo add-apt-repository --yes ppa:ubuntuhandbook1/apps
sudo add-apt-repository --yes ppa:ubuntuhandbook1/audacity
sudo add-apt-repository --yes ppa:ubuntuhandbook1/avidemux
sudo add-apt-repository --yes ppa:ubuntu-idkaart/ppa
sudo add-apt-repository --yes ppa:ubuntu-iremonger/e2fsprogs-xenial
sudo add-apt-repository --yes ppa:ubuntukylin-members/1904tmp
sudo add-apt-repository --yes ppa:ubuntukylin-members/1904updates
sudo add-apt-repository --yes ppa:ubuntukylin-members/daily
sudo add-apt-repository --yes ppa:ubuntukylin-members/ukui-daily
sudo add-apt-repository --yes ppa:ubuntu-mate-dev/ppa
sudo add-apt-repository --yes ppa:ubuntu-mate-dev/precise-mate
sudo add-apt-repository --yes ppa:ubuntu-mate-dev/trusty-mate
sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
sudo add-apt-repository --yes ppa:ubuntustudio-dev/autobuild
sudo add-apt-repository --yes ppa:ubuntustudio-ppa/backports
sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
sudo add-apt-repository --yes ppa:udisks-indicator-team/ppa
sudo add-apt-repository --yes ppa:ufscar/openstack-backports
sudo add-apt-repository --yes ppa:unit193/cherokee
sudo add-apt-repository --yes ppa:unit3/bfgminer
sudo add-apt-repository --yes ppa:unity7maintainers/unity7-desktop
sudo add-apt-repository --yes ppa:unity8-desktop-session-team/custom
sudo add-apt-repository --yes ppa:universal/kodi-deps
sudo add-apt-repository --yes ppa:unnet-pkg-master/icinga-release
sudo add-apt-repository --yes ppa:unnet-pkg-master/infiniband-release
sudo add-apt-repository --yes ppa:unnet-pkg-master/misc
sudo add-apt-repository --yes ppa:unnet-pkg-master/openldap-release
sudo add-apt-repository --yes ppa:unnet-pkg-master/php-release
sudo add-apt-repository --yes ppa:upubuntu-com/conky
sudo add-apt-repository --yes ppa:uvtool-dev/master
sudo add-apt-repository --yes ppa:uvtool-dev/trunk
sudo add-apt-repository --yes ppa:vaiofand/ppa
sudo add-apt-repository --yes ppa:vaiopower/ppa
sudo add-apt-repository --yes ppa:valve-experimental/kernel-bionic
sudo add-apt-repository --yes ppa:valve-experimental/mesa-bionic
sudo add-apt-repository --yes ppa:vanhoof/android-tools-precise
sudo add-apt-repository --yes ppa:varlesh-l/bionic
sudo add-apt-repository --yes ppa:vcclive/freeswitch
sudo add-apt-repository --yes ppa:vdrchuck/myvdr
sudo add-apt-repository --yes ppa:venerix/pkg
sudo add-apt-repository --yes ppa:vidavidorra/personal-tests
sudo add-apt-repository --yes ppa:videolan/stable-daily
sudo add-apt-repository --yes ppa:vidplace7/bluez5
sudo add-apt-repository --yes ppa:vidplace7/bluez5-backports
sudo add-apt-repository --yes ppa:vinator/trusty
sudo add-apt-repository --yes ppa:vinux/vinux-lucid-testing
sudo add-apt-repository --yes ppa:virtubox/tinc
sudo add-apt-repository --yes ppa:vovansrnd/coolreader
sudo add-apt-repository --yes ppa:vshn/apt-dater
sudo add-apt-repository --yes ppa:wasta-linux/cinnamon-3-2
sudo add-apt-repository --yes ppa:wasta-linux/wasta-testing
sudo add-apt-repository --yes ppa:wdaniau/custom
sudo add-apt-repository --yes ppa:wdconinc/ppa-bionic
sudo add-apt-repository --yes ppa:wdconinc/ppa-xenial
sudo add-apt-repository --yes ppa:webaugur/php5.2
sudo add-apt-repository --yes ppa:webispy/grpc
sudo add-apt-repository --yes ppa:webupd8team/gthumb
sudo add-apt-repository --yes ppa:webupd8team/java
sudo add-apt-repository --yes ppa:webupd8team/popcorntime
sudo add-apt-repository --yes ppa:webupd8team/themes
sudo add-apt-repository --yes ppa:webupd8team/tor-browser
sudo add-apt-repository --yes ppa:wenchien/icecream-backport
sudo add-apt-repository --yes ppa:wfg/0ad
sudo add-apt-repository --yes ppa:wfg/0ad.dev
sudo add-apt-repository --yes ppa:widelands-dev/widelands
sudo add-apt-repository --yes ppa:wpilib/toolchain
sudo add-apt-repository --yes ppa:x2go/ppa
sudo add-apt-repository --yes ppa:x2go/stable
sudo add-apt-repository --yes ppa:x3lectric/nvidia-vdpau
sudo add-apt-repository --yes ppa:xav0989/openssh-bp
sudo add-apt-repository --yes ppa:xeros/stepmania
sudo add-apt-repository --yes ppa:xeros/xeros-test
sudo add-apt-repository --yes ppa:xiota/fonts
sudo add-apt-repository --yes ppa:xiota/stuff-1
sudo add-apt-repository --yes ppa:xiota/stuff-2
sudo add-apt-repository --yes ppa:xiota/stuff-3
sudo add-apt-repository --yes ppa:xiota/stuff-5
sudo add-apt-repository --yes ppa:xnox/indigo
sudo add-apt-repository --yes ppa:xorg-edgers/ppa
sudo add-apt-repository --yes ppa:xubuntu-dev/staging
sudo add-apt-repository --yes ppa:xuzhen666/arm
sudo add-apt-repository --yes ppa:yak1ex/llvm
sudo add-apt-repository --yes ppa:yannubuntu/boot-repair
sudo add-apt-repository --yes ppa:yavdr/unstable-vdr
sudo add-apt-repository --yes ppa:ybalrid/ogre-21-trusty
sudo add-apt-repository --yes ppa:ytvwld/asciiquarium
sudo add-apt-repository --yes ppa:ytvwld/syncthing
sudo add-apt-repository --yes ppa:yuri-sucupira/thunar1.6.10-fix
sudo add-apt-repository --yes ppa:zachtib/deluge
sudo add-apt-repository --yes ppa:zak-k/ppa-build
sudo add-apt-repository --yes ppa:zanfur/php5.5
sudo add-apt-repository --yes ppa:zentyal/2.3
sudo add-apt-repository --yes ppa:zerebubuth/ccache
sudo add-apt-repository --yes ppa:zerebubuth/mapnik
sudo add-apt-repository --yes ppa:zhsj/elvish
sudo add-apt-repository --yes ppa:zoralab/bissetii
sudo add-apt-repository --yes ppa:zvonkoko/misc
sudo add-apt-repository --yes ppa:zxcq14/minimize-unity-7
sudo add-apt-repository --yes ppa:zyga/oauth
